// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOH2nA-FuvevOa_tSHQrLG4-q3ntoExVQ',
    appId: '1:459975362038:web:4a02d2ddfb1e0a7f7873d7',
    messagingSenderId: '459975362038',
    projectId: 'mukund-madhav-0',
    authDomain: 'mukund-madhav-0.firebaseapp.com',
    storageBucket: 'mukund-madhav-0.appspot.com',
    measurementId: 'G-6N06N97NJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAjujagYSybyEsXoeLmZBWgosHvOf48t4',
    appId: '1:459975362038:android:0ef2acb20a3cb63e7873d7',
    messagingSenderId: '459975362038',
    projectId: 'mukund-madhav-0',
    storageBucket: 'mukund-madhav-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgoEhzsfKLpP68pLXUCFxxu-wgpvkroWw',
    appId: '1:459975362038:ios:b8a62cc299f2540f7873d7',
    messagingSenderId: '459975362038',
    projectId: 'mukund-madhav-0',
    storageBucket: 'mukund-madhav-0.appspot.com',
    iosBundleId: 'com.example.mongodb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgoEhzsfKLpP68pLXUCFxxu-wgpvkroWw',
    appId: '1:459975362038:ios:b8a62cc299f2540f7873d7',
    messagingSenderId: '459975362038',
    projectId: 'mukund-madhav-0',
    storageBucket: 'mukund-madhav-0.appspot.com',
    iosBundleId: 'com.example.mongodb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOH2nA-FuvevOa_tSHQrLG4-q3ntoExVQ',
    appId: '1:459975362038:web:a0cd32ef41e0a0ae7873d7',
    messagingSenderId: '459975362038',
    projectId: 'mukund-madhav-0',
    authDomain: 'mukund-madhav-0.firebaseapp.com',
    storageBucket: 'mukund-madhav-0.appspot.com',
    measurementId: 'G-BXFNPSC6XS',
  );
}
